# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

language: java

dist: trusty

matrix:
  allow_failures:
  - openjdk-ea

jdk:
- openjdk8
- openjdk11
- openjdk14
jobs:
  include:
  - stage: deploy
    jdk: openjdk8
    script: ./gradlew ciPerformRelease

#don't build tags
branches:
  except:
  - /^v\d/

# Below skips the installation step completely (https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step)
install:
- true

script:
- ./gradlew --version
- ./gradlew build
